model_list:
  - model_name: local-ollama-llama3
    litellm_params:
      model: ollama/llama3.1
      api_base: os.environ/OLLAMA_API_BASE

  - model_name: cloud-openai-gpt-4o-mini
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY
      api_base: os.environ/OPENAI_API_BASE

  - model_name: cloud-anthropic-claude-3-5-sonnet
    litellm_params:
      model: anthropic/claude-3-5-sonnet-20240620
      api_key: os.environ/ANTHROPIC_API_KEY
      api_base: os.environ/ANTHROPIC_API_BASE

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
